import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/user/entities/user.entity';

export class LoginResponseDto {
  @ApiProperty({
    description: 'JWT generated by login',
    example: 'AUTOMATICALLY GENERATED TOKEN',
  })
  token?: string;

  @ApiProperty({
    description: 'Authenticated user data',
  })
  user?: User;

  @ApiProperty({
    description: 'Login status',
    example: true,
  })
  login?: boolean;

  @ApiProperty({
    description: 'message when login is false',
    example: 'Usuário novo, por favor crie uma senha',
  })
  message?: string;

  @ApiProperty({
    description:
      'JWT crypt generated by login when user is new, used as parameter to create password',
    example: 'AUTOMATICALLY GENERATED TOKEN',
  })
  tokenUrl?: string;
}

export class LogoutResponseDto {
  @ApiProperty({
    description: 'Logout boolean',
    example: 'true',
  })
  logout: boolean;
}
